export const cards = [
  {
    imageSrc: "/assets/card/1.jpg",
    imageAlt: "card",
    attack: 8,
    health: 5,
    level: 1,
  },
  {
    imageSrc: "/assets/card/2.jpg",
    imageAlt: "card",
    attack: 8,
    health: 5,
    level: 1,
  },
  {
    imageSrc: "/assets/card/3.jpg",
    imageAlt: "card",
    attack: 8,
    health: 5,
    level: 1,
  },
  {
    imageSrc: "/assets/card/4.jpg",
    imageAlt: "card",
    attack: 8,
    health: 5,
    level: 1,
  },
  {
    imageSrc: "/assets/card/5.jpg",
    imageAlt: "card",
    attack: 8,
    health: 5,
    level: 1,
  },
  {
    imageSrc: "/assets/card/6.jpg",
    imageAlt: "card",
    attack: 8,
    health: 5,
    level: 1,
  },
  {
    imageSrc: "/assets/card/7.jpg",
    imageAlt: "card",
    attack: 8,
    health: 5,
    level: 1,
  },
  {
    imageSrc: "/assets/card/8.jpg",
    imageAlt: "card",
    attack: 8,
    health: 5,
    level: 1,
  },
  {
    imageSrc: "/assets/card/9.jpg",
    imageAlt: "card",
    attack: 8,
    health: 5,
    level: 1,
  },
  {
    imageSrc: "/assets/card/10.jpg",
    imageAlt: "card",
    attack: 8,
    health: 5,
    level: 1,
  },
  {
    imageSrc: "/assets/card/11.jpg",
    imageAlt: "card",
    attack: 8,
    health: 5,
    level: 1,
  },

]
