// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { Name, NameTableId } from "./tables/Name.sol";
import { Image, ImageTableId } from "./tables/Image.sol";
import { Ownership, OwnershipTableId } from "./tables/Ownership.sol";
import { CustomUniqueEntity, CustomUniqueEntityTableId } from "./tables/CustomUniqueEntity.sol";
import { DeckCard, DeckCardTableId } from "./tables/DeckCard.sol";
import { PlayerCard, PlayerCardData, PlayerCardTableId } from "./tables/PlayerCard.sol";
import { Card, CardTableId } from "./tables/Card.sol";
import { HeroCard, HeroCardData, HeroCardTableId } from "./tables/HeroCard.sol";
import { ItemCard, ItemCardData, ItemCardTableId } from "./tables/ItemCard.sol";
import { Duel, DuelData, DuelTableId } from "./tables/Duel.sol";
import { PlayerInDuel, PlayerInDuelData, PlayerInDuelTableId } from "./tables/PlayerInDuel.sol";
import { TeamHero, TeamHeroTableId } from "./tables/TeamHero.sol";
import { TeamItem, TeamItemTableId } from "./tables/TeamItem.sol";
import { DuelPoints, DuelPointsTableId } from "./tables/DuelPoints.sol";
