const DECK_LENGTH: u8 = 12;
const TEAM_LENGTH: u8 = 4;
const DUEL_ROUND_DEADLINE: u8 = 45;
const WINNER_POINTS: u8 = 2;

const CARD_UNIQUE_ENTITY_TABLE_ID: felt252 = 1;
const PLAYER_CARD_UNIQUE_ENTITY_TABLE_ID: felt252 = 2;
const DUEL_UNIQUE_ENTITY_TABLE_ID: felt252 = 3;

const CARD_UNKNOWN: u8 = 0;
const CARD_HERO: u8 = 1;
const CARD_ITEM: u8 = 2;