projectName: abc
nameSpace: main
appType:
  frontend: webapp

replicaSet: 1
minReplicas: 1
maxReplicas: 3
averageUtilization: 70


webappContainerService:
  type: ClusterIP  # {{ .Values.webappContainerService.type }}
  port: 2015       # {{ .Values.webappContainerService.port }}

anvilContainerService:
  type: ClusterIP  # {{ .Values.anvilContainerService.type }}
  port: 8545       # {{ .Values.anvilContainerService.port }}


domainName: oostvoort.work                # {{ .Values.domainName }}

subDomainName: 
  abc: abc.aw                 # {{ .Values.subDomainName.abc }}

dockerImage: oostvoort/abc:latest