---
apiVersion: v1
kind: Service
metadata:
 name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}
 namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
spec:
 type: {{ .Values.webappContainerService.type }}
 ports:
 - targetPort: {{ .Values.webappContainerService.port }}
   port: {{ .Values.webappContainerService.port }}
 selector:
   app: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}

---
apiVersion: v1
kind: Service
metadata:
 name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}-anvil
 namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
spec:
 type: {{ .Values.anvilContainerService.type }}
 ports:
 - targetPort: {{ .Values.anvilContainerService.port }}
   port: {{ .Values.anvilContainerService.port }}
 selector:
   app: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}